version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    container_name: app
    build: .
    command: bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    container_name: worker
    build: .
    command: celery -A src.celery_worker.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis

  flower:
    container_name: flower
    build: .
    command: celery -A src.celery_worker.celery_app flower --port=5555
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - redis
      - worker