services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
  api:
    container_name: hudddle_api
    build: .
    ports:
      - "8000:80"
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 80 --app-dir app_src
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      MAIL_STARTTLS: True
      MAIL_SSL_TLS: False
      USE_CREDENTIALS: True
      VALIDATE_CERTS: True
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      GOOGLE_AUTH_ENDPOINT: ${GOOGLE_AUTH_ENDPOINT}
      GOOGLE_TOKEN_ENDPOINT: ${GOOGLE_TOKEN_ENDPOINT}
      GOOGLE_USERINFO_ENDPOINT: ${GOOGLE_USERINFO_ENDPOINT}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      GROQ_API_KEY: ${GROQ_API_KEY}
      DG_API_KEY: ${DG_API_KEY}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      DOMAIN: ${DOMAIN}
      HUDDDLE_LINK: ${HUDDDLE_LINK}
    depends_on:
      - redis
  celery_worker:
    container_name: celery_worker_1
    command: celery -A app_src.celery_task worker --loglevel=info --autoscale=1,10 -Q emails,images,sessions
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      PYTHONPATH: /app
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      MAIL_STARTTLS: True
      MAIL_SSL_TLS: False
      USE_CREDENTIALS: True
      VALIDATE_CERTS: True
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      GOOGLE_AUTH_ENDPOINT: ${GOOGLE_AUTH_ENDPOINT}
      GOOGLE_TOKEN_ENDPOINT: ${GOOGLE_TOKEN_ENDPOINT}
      GOOGLE_USERINFO_ENDPOINT: ${GOOGLE_USERINFO_ENDPOINT}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      GROQ_API_KEY: ${GROQ_API_KEY}
      DG_API_KEY: ${DG_API_KEY}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      DOMAIN: ${DOMAIN}
      HUDDDLE_LINK: ${HUDDDLE_LINK}
    depends_on:
      - redis
      - api
  flower:
    container_name: celery_flower
    image: mher/flower:latest
    command: celery flower --broker=${CELERY_BROKER_URL} --address=0.0.0.0 --port=5555
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      FLOWER_BASIC_AUTH: ${FLOWER_USER}:${FLOWER_PASSWORD}
      FLOWER_PURGE_OFFLINE_WORKERS: 30
      FLOWER_PERSISTENT: True
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker

