"""Fix live session tracking

Revision ID: e665e3f89a8b
Revises: 72c74c867b96
Create Date: 2025-10-25 04:55:08.607611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e665e3f89a8b'
down_revision: Union[str, None] = '72c74c867b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_live_session_workroom_id', sa.UUID(), nullable=True, comment='Tracks the workroom where user currently has an active live session'))
    op.create_foreign_key('fk_user_current_live_session_workroom', 'users', 'workrooms', ['current_live_session_workroom_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('workroom_live_sessions', sa.Column('is_ending', sa.Boolean(), nullable=True))
    op.execute("UPDATE workroom_live_sessions SET is_ending = FALSE WHERE is_ending IS NULL")
    op.alter_column('workroom_live_sessions', 'is_ending', nullable=False)
    op.alter_column('workroom_live_sessions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_column('workroom_live_sessions', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workroom_live_sessions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('workroom_live_sessions', 'start_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('workroom_live_sessions', 'is_ending')
    op.drop_constraint('fk_user_current_live_session_workroom', 'users', type_='foreignkey')
    op.drop_column('users', 'current_live_session_workroom_id')
    # ### end Alembic commands ###
